import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.border.EmptyBorder;
import javax.swing.JTextField;

public class Buscador extends JFrame {

	private JPanel contentPane;
	private JTextField textField;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					frame = new Buscador();
					frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */

	private static Buscador frame;
	private JTextField nameField;
	private JTextField mailField;
	private JPasswordField passwordField;
	private JPasswordField passwordFieldV;
	private JLabel lblUsuario;
	private JLabel lblCorreo;
	private JLabel lblPassword;
	private JLabel lblRepetirPassword;
	private JLabel lblPais;
	private JLabel lblRegistro;
	private JButton btnRegistrarse;


	/**
	 * Create the frame.
	 */
	public Buscador() {
		setTitle("Buscador Puntos Wifi");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(500, 100, 600, 350);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		//Poner Usuario
		JComboBox<String> comboBox4 = new JComboBox<String>();
		contentPane.add(comboBox4);
		comboBox4.setBounds(170,70,350,20);
		comboBox4.addItem("");
		comboBox4.addItem("Agencia de Actividades");
		comboBox4.addItem("Biblioteca Publica Municipal Aluche");
		comboBox4.addItem("Biblioteca Publica Municipal Ana Maria Matute");
		comboBox4.addItem("Biblioteca Publica Municipal Angel Gonzalez");
		comboBox4.addItem("Biblioteca Publica Municipal Buenavista");
		comboBox4.addItem("Biblioteca Publica Municipal Canillejas");
		comboBox4.addItem("Biblioteca Publica Municipal Ciudad Lineal");
		comboBox4.addItem("Biblioteca Publica Municipal Conde Duque");
		comboBox4.addItem("Biblioteca Publica Municipal Damaso Alonso");
		comboBox4.addItem("Biblioteca Publica Municipal Eugenio Tria");
		comboBox4.addItem("Biblioteca Publica Municipal Francisco Ayala");
		comboBox4.addItem("Biblioteca Publica Municipal Francisco Ibañez");
		comboBox4.addItem("Biblioteca Publica Municipal Gabriel Garcia Marquez");
		comboBox4.addItem("Biblioteca Publica Municipal Gerardo Diego");
		comboBox4.addItem("Biblioteca Publica Municipal Gloria Fuertes");
		comboBox4.addItem("Biblioteca Publica Municipal Huerta de la Salud");
		comboBox4.addItem("Biblioteca Publica Municipal Ivan de Vargas");
		comboBox4.addItem("Biblioteca Publica Municipal Jose Hierro");
		comboBox4.addItem("Biblioteca Publica Municipal Jose Saramago");
		comboBox4.addItem("Biblioteca Publica Municipal La Chata");
		comboBox4.addItem("Biblioteca Publica Municipal La Elipa");
		comboBox4.addItem("Biblioteca Publica Municipal Manuel Vazquez Montalban");
		comboBox4.addItem("Biblioteca Publica Municipal Maria Lejarraga");
		comboBox4.addItem("Biblioteca Publica Municipal Maria Zambrano");
		comboBox4.addItem("Biblioteca Publica Municipal Mario Vargas Llosa");
		comboBox4.addItem("Biblioteca Publica Municipal Miguel Delibes");
		comboBox4.addItem("Biblioteca Publica Municipal Pablo Neruda");
		comboBox4.addItem("Biblioteca Publica Municipal Pio Baroja");
		comboBox4.addItem("Biblioteca Publica Municipal Portazgo");
		comboBox4.addItem("Biblioteca Publica Municipal Pozo del Tio Raimundo");
		comboBox4.addItem("Biblioteca Publica Municipal San Blas");
		comboBox4.addItem("Biblioteca Publica Municipal Vallecas");
		comboBox4.addItem("Biblioteca Publica Municipal Vicalvaro");
		comboBox4.addItem("Casa del Empleo");
		comboBox4.addItem("Centro Cultural Agustin Diaz");
		comboBox4.addItem("Centro Cultural Alfredo Kraus");
		comboBox4.addItem("Centro Cultural Almirante Churruca");
		comboBox4.addItem("Centro Cultural Aravaca");
		comboBox4.addItem("Centro Cultural Buenavista");
		comboBox4.addItem("Centro Cultural Buero Vallejo");
		comboBox4.addItem("Centro Cultural Carril del Conde ");
		comboBox4.addItem("Centro Cultural Casa de Vacas");
		comboBox4.addItem("Centro Cultural Casa del Reloj");
		comboBox4.addItem("Centro Cultural Ciudad Pegaso");
		comboBox4.addItem("Centro Cultural Dotacional Integrado Arganzuela");
		comboBox4.addItem("Centro Cultural Eduardo Urculo");
		comboBox4.addItem("Centro Cultural el Madroño");
		comboBox4.addItem("Centro Cultural el Torito");
		comboBox4.addItem("Centro Cultural Fernando de los Rios");
		comboBox4.addItem("Centro Cultural Galileo");
		comboBox4.addItem("Centro Cultural Gloria Fuertes");
		comboBox4.addItem("Centro Cultural Hortaleza");
		comboBox4.addItem("Centro Cultural Huerta de la Salud");
		comboBox4.addItem("Centro Cultural Jose Luis Lopez Vazquez");
		comboBox4.addItem("Centro Cultural Jose Luis Sampedro");
		comboBox4.addItem("Centro Cultural Juan Gris");
		comboBox4.addItem("Centro Cultural Julio Cortazar");
		comboBox4.addItem("Centro Cultural la Elipa");
		comboBox4.addItem("Centro Cultural La Vaguada");
		comboBox4.addItem("Centro Cultural Las Californias");
		comboBox4.addItem("Centro Cultural Lope de Vega");
		comboBox4.addItem("Centro Cultural Los Rosales");
		comboBox4.addItem("Centro Cultural Mercado de Ibiza");
		comboBox4.addItem("Centro Cultural Meseta de Orcasitas");
		comboBox4.addItem("Centro Cultural Miguel Hernandez");
		comboBox4.addItem("Centro Cultural Nicolas Salmeron");
		comboBox4.addItem("Centro Cultural Orcasur");
		comboBox4.addItem("Centro Cultural Pozo del tio Raimundo");
		comboBox4.addItem("Centro Cultural Puerta de Toledo");
		comboBox4.addItem("Centro Cultural Rafael Altamira, antes Palacete Quinta del Berro");
		comboBox4.addItem("Centro Cultural San Juan Bautista");
		comboBox4.addItem("Centro Cultural Sara Montiel");
		comboBox4.addItem("Centro Cultural Teresa de Calcuta");
		comboBox4.addItem("Centro Cultural Usera");
		comboBox4.addItem("Centro Cultural Valdebernardo");
		comboBox4.addItem("Centro Cultural Zazuar");
		comboBox4.addItem("Centro Cultural - Centro Socio Cultural Villa de Barajas");
		comboBox4.addItem("Centro de Formacion de Ancora");
		comboBox4.addItem("Centro de Formacion de Barajas");
		comboBox4.addItem("Centro de Salud Santa Hortensia");
		comboBox4.addItem("Centro de Servicios Sociales Dehesa de la Villa");
		comboBox4.addItem("Centro de Servicios Sociales Eduardo Minguito");
		comboBox4.addItem("Centro de Servicios Sociales Entrevias");
		comboBox4.addItem("Centro de Servicios Sociales Guindalera");
		comboBox4.addItem("Centro de Servicios Sociales Luis Vives");
		comboBox4.addItem("Centro de Servicios Sociales Pablo Neruda");
		comboBox4.addItem("Centro de Servicios Sociales San Diego");
		comboBox4.addItem("Centro de Servicios Sociales Santa Hortensia");
		comboBox4.addItem("Centro Municipal de Mayores 'Alfonso XII'");
		comboBox4.addItem("Centro Municipal de Mayores 'Anton Martin'");
		comboBox4.addItem("Centro Municipal de Mayores 'Antonio Machado'");
		comboBox4.addItem("Centro Municipal de Mayores 'Ascao'");
		comboBox4.addItem("Centro Municipal de Mayores 'Blasco de Garay'");
		comboBox4.addItem("Centro Municipal de Mayores 'Bucaramanga'");
		comboBox4.addItem("Centro Municipal de Mayores 'Campamento'");
		comboBox4.addItem("Centro Municipal de Mayores 'Casa del Reloj'");
		comboBox4.addItem("Centro Municipal de Mayores 'Ciudad de Mejico'");
		comboBox4.addItem("Centro Municipal de Mayores 'Daroca'");
		comboBox4.addItem("Centro Municipal de Mayores 'Dehesa de la Villa'");
		comboBox4.addItem("Centro Municipal de Mayores 'Dos Amigos'");
		comboBox4.addItem("Centro Municipal de Mayores 'Eduardo Minguito'");
		comboBox4.addItem("Centro Municipal de Mayores 'El Almendro'");
		comboBox4.addItem("Centro Municipal de Mayores 'El Pozo'");
		comboBox4.addItem("Centro Municipal de Mayores 'Entrevias'");
		comboBox4.addItem("Centro Municipal de Mayores 'Infante Don Juan'");
		comboBox4.addItem("Centro Municipal de Mayores 'Islas Filipinas'");
		comboBox4.addItem("Centro Municipal de Mayores 'La Guindalera'");
		comboBox4.addItem("Centro Municipal de Mayores 'La Vaguada'");
		comboBox4.addItem("Centro Municipal de Mayores 'Leñero'");
		comboBox4.addItem("Centro Municipal de Mayores 'Lucero'");
		comboBox4.addItem("Centro Municipal de Mayores 'Luis Vives'");
		comboBox4.addItem("Centro Municipal de Mayores 'Maestro Alonso'");
		comboBox4.addItem("Centro Municipal de Mayores 'Maria Zambrano'");
		comboBox4.addItem("Centro Municipal de Mayores 'Nicanor Barros'");
		comboBox4.addItem("Centro Municipal de Mayores 'Nuestra Señora del Carmen'");
		comboBox4.addItem("Centro Municipal de Mayores 'Pablo Neruda'");
		comboBox4.addItem("Centro Municipal de Mayores 'Pamplona'");
		comboBox4.addItem("Centro Municipal de Mayores 'Pio Baroja'");
		comboBox4.addItem("Centro Municipal de Mayores 'Principe de Asturias'");
		comboBox4.addItem("Centro Municipal de Mayores 'Prosperidad Santa Hortensia'");
		comboBox4.addItem("Centro Municipal de Mayores 'San Diego'");
		comboBox4.addItem("Centro Municipal de Mayores 'San Juan Bautista'");
		comboBox4.addItem("Centro Municipal de Mayores 'San Vicente de Paul'");
		comboBox4.addItem("Centro Municipal de Mayores 'Santa Engracia'");
		comboBox4.addItem("Centro Municipal de Mayores 'Teresa de Calcuta'");
		comboBox4.addItem("Centro Municipal de Mayores 'Villa de Vallecas'");
		comboBox4.addItem("Centro Sociocultural Siena");
		comboBox4.addItem("Centro Sociocultural Agata");
		comboBox4.addItem("Centro Sociocultural Alberto Sanchez");
		comboBox4.addItem("Centro Sociocultural Alfonso XII");
		comboBox4.addItem("Centro Sociocultural Blasco Ibañez");
		comboBox4.addItem("Centro Sociocultural Bohemios");
		comboBox4.addItem("Centro Sociocultural Canovas del Castillo");
		comboBox4.addItem("Centro Sociocultural Ciudad Lineal");
		comboBox4.addItem("Centro Sociocultural de Moratalaz");
		comboBox4.addItem("Centro Sociocultural Eduardo Chillida");
		comboBox4.addItem("Centro Sociocultural El Greco");
		comboBox4.addItem("Centro Sociocultural Jose Espronceda");
		comboBox4.addItem("Centro Sociocultural Juvenil de Usera");
		comboBox4.addItem("Centro Sociocultural Latina");
		comboBox4.addItem("Centro Sociocultural Lavapies");
		comboBox4.addItem("Centro Sociocultural Luis Gonzaga");
		comboBox4.addItem("Centro Sociocultural Maestro Alonso");
		comboBox4.addItem("Centro Sociocultural Marconi");
		comboBox4.addItem("Centro Sociocultural Miguel de Cervantes");
		comboBox4.addItem("Centro Sociocultural Rafael de Leon");
		comboBox4.addItem("Centro Sociocultural Rosario de Acuña");
		comboBox4.addItem("Centro Sociocultural San Cristobal de los Angeles");
		comboBox4.addItem("Centro Sociocultural San Fermin");
		comboBox4.addItem("Centro Sociocultural Santa Petronila");
		comboBox4.addItem("Centro Sociocultural Talleres de Creatividad");
		comboBox4.addItem("Centro Sociocultural Tetuan");
		comboBox4.addItem("Centro Sociocultural Valle Inclan");
		comboBox4.addItem("Centro Sociocultural Valverde");
		comboBox4.addItem("Centro Sociocultural Vicalvaro");
		comboBox4.addItem("Centro Cent");
		comboBox4.addItem("Conde Duque");
		comboBox4.addItem("Hemeroteca Municipal");
		comboBox4.addItem("Museo de Historia de Madrid");
		comboBox4.addItem("Museo de San Isidro");
		comboBox4.addItem("Oficina Auxiliar de Atencion a la Ciudadania de El Pardo. Oficina de Atencion a la Ciudadania");
		comboBox4.addItem("Oficina Auxiliar de Atencion a la Ciudadania de Valverde. Oficina de Atencion a la Ciudadania");
		comboBox4.addItem("Oficina de Atencion a la Ciudadania.");
		comboBox4.addItem("Oficina de Atencion Integral al Contribuyente");
		comboBox4.addItem("Oficina de objetos perdidos del Ayuntamiento de Madrid");
		comboBox4.addItem("Oficina especializada del Servicio de Estacionamiento Regulado, APR y Biciregistro");
		comboBox4.addItem("Pabellon de los Jardines de Cecilio Rodriguez");
		comboBox4.addItem("Punto de Atencion Social El Quer");
		comboBox4.addItem("Sala de estudio Canovas del Castillo");
		comboBox4.addItem("Sala de estudio El Madroño");
		comboBox4.addItem("Sala de estudio Luis Garcia Berlanga");
		comboBox4.addItem("Sala de estudio Motilla del Palancar");
		comboBox4.addItem("Sala de estudio Pilares");
		comboBox4.addItem("Sala de estudio Valdebernardo");
		comboBox4.addItem("Sala de estudio y lectura Arquitecto Juan de Herrera");
		comboBox4.addItem("Sala de estudio y lectura Escritor Pedro de Repide ");
		lblUsuario = new JLabel("Nombre Lugar: ");
		contentPane.add(lblUsuario);
		lblUsuario.setBounds(50,70,100,20);
		//Poner Correo
		JComboBox<String> comboBox3 = new JComboBox<String>();
		contentPane.add(comboBox3);
		comboBox3.setBounds(170,100,350,20);
		comboBox3.addItem("");
		comboBox3.addItem("Arganzuela");
		comboBox3.addItem("Barajas");
		comboBox3.addItem("Carabanchel");
		comboBox3.addItem("Centro");
		comboBox3.addItem("Chamartin");
		comboBox3.addItem("Chamberi");
		comboBox3.addItem("Ciudad Lineal");
		comboBox3.addItem("Fuencarral-El Pardo");
		comboBox3.addItem("Hortaleza");
		comboBox3.addItem("Latina");
		comboBox3.addItem("Moncloa-Aravaca");
		comboBox3.addItem("Moratalaz");
		comboBox3.addItem("Puente de Vallecas");
		comboBox3.addItem("Retiro");
		comboBox3.addItem("Salamanca");
		comboBox3.addItem("San Blas");
		comboBox3.addItem("Tetuan");
		comboBox3.addItem("Usera");
		comboBox3.addItem("Vicalvaro");
		comboBox3.addItem("Villa de Vallecas");
		comboBox3.addItem("Villaverde");
		lblCorreo = new JLabel("Distrito: ");
		contentPane.add(lblCorreo);
		lblCorreo.setBounds(50,100,100,20);
		//Poner Password
		JComboBox<String> comboBox2 = new JComboBox<String>();
		contentPane.add(comboBox2);
		comboBox2.setBounds(170,130,350,20);
		comboBox2.addItem("");
		comboBox2.addItem("Adelfas");
		comboBox2.addItem("Alameda de Osuna");
		comboBox2.addItem("Almenara");
		comboBox2.addItem("Almendrales");
		comboBox2.addItem("Aluche");
		comboBox2.addItem("Apostol Santiago");
		comboBox2.addItem("Arapiles");
		comboBox2.addItem("Arcos (Madrid)");
		comboBox2.addItem("Arguelles");
		comboBox2.addItem("Barrio de Puerta del Angel");
		comboBox2.addItem("Bellas Vistas");
		comboBox2.addItem("Berruguete");
		comboBox2.addItem("Butarque");
		comboBox2.addItem("Campamento");
		comboBox2.addItem("Canillas");
		comboBox2.addItem("Canillejas");
		comboBox2.addItem("Casa de Campo");
		comboBox2.addItem("Casco Historico de Barajas");
		comboBox2.addItem("Casco Historico de Vallecas");
		comboBox2.addItem("Casco Historico de Vicalvaro");
		comboBox2.addItem("Castilla");
		comboBox2.addItem("Ciudad Jardin");
		comboBox2.addItem("Corralejos");
		comboBox2.addItem("El Pardo");
		comboBox2.addItem("El Pilar");
		comboBox2.addItem("Embajadores");
		comboBox2.addItem("Entrevias");
		comboBox2.addItem("Fontarron");
		comboBox2.addItem("Fuente del Berro");
		comboBox2.addItem("Ibiza");
		comboBox2.addItem("Jeronimos");
		comboBox2.addItem("Justicia");
		comboBox2.addItem("La chopera");
		comboBox2.addItem("La Elipa neighborhood, Madrid");
		comboBox2.addItem("La Guindalera");
		comboBox2.addItem("La Paz");
		comboBox2.addItem("Las Acacias");
		comboBox2.addItem("Las Aguilas");
		comboBox2.addItem("Las Delicias (Madrid)");
		comboBox2.addItem("Legazpi");
		comboBox2.addItem("Los Angeles");
		comboBox2.addItem("Los Rosales");
		comboBox2.addItem("Lucero");
		comboBox2.addItem("Media Legua");
		comboBox2.addItem("Mirasierr");
		comboBox2.addItem("Moscardo");
		comboBox2.addItem("Niño Jesus");
		comboBox2.addItem("Numancia");
		comboBox2.addItem("Opañel");
		comboBox2.addItem("Orcasitas");
		comboBox2.addItem("Orcasur");
		comboBox2.addItem("Pacifico");
		comboBox2.addItem("Palacio");
		comboBox2.addItem("Palomeras Bajas");
		comboBox2.addItem("Palomeras Sureste");
		comboBox2.addItem("Palos de Monguer");
		comboBox2.addItem("Pavones");
		comboBox2.addItem("PEÑA GRANDE");
		comboBox2.addItem("Pinar del Rey");
		comboBox2.addItem("Pradolongo");
		comboBox2.addItem("Prosperidad");
		comboBox2.addItem("Pueblo Nuevo");
		comboBox2.addItem("Quintana");
		comboBox2.addItem("Rios Rosas");
		comboBox2.addItem("Recoletos");
		comboBox2.addItem("Rejas");
		comboBox2.addItem("Rosas");
		comboBox2.addItem("San Cristobal");
		comboBox2.addItem("San Diego");
		comboBox2.addItem("San Fermin (Madrid)");
		comboBox2.addItem("San Isidro");
		comboBox2.addItem("San Juan Bautista");
		comboBox2.addItem("Santa Eugenia");
		comboBox2.addItem("Universidad");
		comboBox2.addItem("Valdebernardo");
		comboBox2.addItem("Valdefuentes");
		comboBox2.addItem("Valdezarza");
		comboBox2.addItem("Vallehermoso");
		comboBox2.addItem("Ventas");
		comboBox2.addItem("Villaverde Alto, Casco Historico de Villaverde");
		comboBox2.addItem("Vinateros");
		comboBox2.addItem("Vista Alegre");
		lblPassword = new JLabel("Barrio: ");
		contentPane.add(lblPassword);
		lblPassword.setBounds(50,130,100,20);
		//Verificar Password
		JComboBox<String> comboBox1 = new JComboBox<String>();
		contentPane.add(comboBox1);
		comboBox1.setBounds(170,160,350,20);
		comboBox1.addItem("");
		comboBox1.addItem("Albufera");
		comboBox1.addItem("ALIAGA");
		comboBox1.addItem("ANCORA");
		comboBox1.addItem("ANTONIA LANCHA");
		comboBox1.addItem("Antonio Machado");
		comboBox1.addItem("ARROYO BELINCOSO");
		comboBox1.addItem("ARROYO BUENO");
		comboBox1.addItem("ASCAO");
		comboBox1.addItem("ARGANDA");
		comboBox1.addItem("ARZOBISPO MORCILLO");
		comboBox1.addItem("ASOCIACION");
		comboBox1.addItem("Barcela");
		comboBox1.addItem("Blasco de Garay");
		comboBox1.addItem("BOADILLA DEL MONTE");
		comboBox1.addItem("BOLTAÑA");
		comboBox1.addItem("BOTICA");
		comboBox1.addItem("Bueso de Pineda");
		comboBox1.addItem("Bustamante");
		comboBox1.addItem("CABEZA");
		comboBox1.addItem("CAMARENA");
		comboBox1.addItem("CANARIAS");
		comboBox1.addItem("CANTABRIA");
		comboBox1.addItem("CANTALAPIEDRA");
		comboBox1.addItem("Carretera de Canillas");
		comboBox1.addItem("CARRIL DEL CONDE");
		comboBox1.addItem("CASTROSERNA");
		comboBox1.addItem("CIBELES");
		comboBox1.addItem("Ciudad de Barcelona");
		comboBox1.addItem("COLOMBIA");
		comboBox1.addItem("COLONIA MARCONI");
		comboBox1.addItem("COMANDANTE FORTEA");
		comboBox1.addItem("CONCEJO DE TEVERGA");
		comboBox1.addItem("Conde Duque");
		comboBox1.addItem("CUESTA");
		comboBox1.addItem("DAROCA");
		comboBox1.addItem("de Almansa");
		comboBox1.addItem("de Arcentales");
		comboBox1.addItem("de Atocha");
		comboBox1.addItem("de Bravo Murillo");
		comboBox1.addItem("de Fuencarral");
		comboBox1.addItem("de la Fuente Carrantona");
		comboBox1.addItem("de la Reina Victoria");
		comboBox1.addItem("DE LA ZARZA");
		comboBox1.addItem("DE LAS GLORIETAS");
		comboBox1.addItem("DE LOS COMUNEROS DE CASTILLA");
		comboBox1.addItem("de los Dos Amigos");
		comboBox1.addItem("de los Toreros");
		comboBox1.addItem("de Mira del Rio");
		comboBox1.addItem("de Monforte de Lemos");
		comboBox1.addItem("de Raimundo Fernandez Villaverde");
		comboBox1.addItem("de Santa Engracia");
		comboBox1.addItem("de Santa Hortensia");
		comboBox1.addItem("de Velazquez");
		comboBox1.addItem("del Arroyo del Olivar");
		comboBox1.addItem("del Maestro Alonso");
		comboBox1.addItem("del Principe de Vergara");
		comboBox1.addItem("del Sacramento");
		comboBox1.addItem("DOCTOR MARTIN AREVALO");
		comboBox1.addItem("DON ANTONIO DE ANDRES");
		comboBox1.addItem("Donoso Cortes");
		comboBox1.addItem("Duque de Fernandez");
		comboBox1.addItem("EL GRECO");
		comboBox1.addItem("ENCOMIENDA DE PALACIOS");
		comboBox1.addItem("ENRIQUE D'ALMONTE");
		comboBox1.addItem("ESTAFETA");
		comboBox1.addItem("FEBRERO");
		comboBox1.addItem("FEDERICO GARCIA LORCA");
		comboBox1.addItem("FELIPE CASTRO");
		comboBox1.addItem("Francos Rodriguez");
		comboBox1.addItem("FUENTE DEL TIRO");
		comboBox1.addItem("Galileo");
		comboBox1.addItem("Gran Via de San Francisco");
		comboBox1.addItem("GRANJA DE TORREHERMOSA");
		comboBox1.addItem("General Ricardos");
		comboBox1.addItem("GERARDO DIEGO");
		comboBox1.addItem("HIERRO");
		comboBox1.addItem("IBIZA");
		comboBox1.addItem("INDALECIO PRIETO");
		comboBox1.addItem("Institucion Libre de Enseñanza");
		comboBox1.addItem("ISLAS AZORES");
		comboBox1.addItem("ISLA DE ONS");
		comboBox1.addItem("JAVIER DE MIGUEL");
		comboBox1.addItem("JULIO AGUIRRE");
		comboBox1.addItem("LADRERA DE LOS ALMENDROS");
		comboBox1.addItem("LAGO TITICACA");
		comboBox1.addItem("LAS AGUILAS");
		comboBox1.addItem("LEÑEROS");
		comboBox1.addItem("LEONOR GONGORA");
		comboBox1.addItem("LOS BOHEMIOS");
		comboBox1.addItem("LOS PILARES");
		comboBox1.addItem("LOS ROSALES");
		comboBox1.addItem("LOGROÑO");
		comboBox1.addItem("LUIS PEIDRO");
		comboBox1.addItem("Mantuano");
		comboBox1.addItem("MAR DE LAS ANTILLAS");
		comboBox1.addItem("MARIA DEL CARMEN");
		comboBox1.addItem("MARIA MARTINEZ OVIOL");
		comboBox1.addItem("Maria Sevilla Diago");
		comboBox1.addItem("MANUEL FERRERO");
		comboBox1.addItem("MERCURIO");
		comboBox1.addItem("MOLINO");
		comboBox1.addItem("Monasterio");
		comboBox1.addItem("Moncloa Palace");
		comboBox1.addItem("MONTE AYA");
		comboBox1.addItem("MONTE OLIVETI");
		comboBox1.addItem("MORATALAZ");
		comboBox1.addItem("MORET");
		comboBox1.addItem("MOTILLA DEL PALANCAR");
		comboBox1.addItem("NAVIO");
		comboBox1.addItem("NUESTRA SEÑORA DEL VILLAR");
		comboBox1.addItem("Pamplona");
		comboBox1.addItem("Paseo de la Chopera");
		comboBox1.addItem("PICO MAMPODRE");
		comboBox1.addItem("PILAR DE ZARAGOZA");
		comboBox1.addItem("PINAZO");
		comboBox1.addItem("PIO BAROJA");
		comboBox1.addItem("POETA BLAS DE OTERO");
		comboBox1.addItem("PRADERA DE VAQUERIZAS");
		comboBox1.addItem("PRINCESA DE EBOLI");
		comboBox1.addItem("PUEBLO ");
		comboBox1.addItem("Rafael Finat");
		comboBox1.addItem("RAFAELA YBARRA");
		comboBox1.addItem("RAMON POWER");
		comboBox1.addItem("RISCO DE PELOCHE ");
		comboBox1.addItem("RODRIGO DE ARANA");
		comboBox1.addItem("SAN ANDRES");
		comboBox1.addItem("San Justo");
		comboBox1.addItem("SAN NEMESIO");
		comboBox1.addItem("SAN ROMAN DEL VALLE");
		comboBox1.addItem("SANTA FELICIDAD");
		comboBox1.addItem("SANTA VIRGILIA");
		comboBox1.addItem("SEPTIMA");
		comboBox1.addItem("SERRADILLA");
		comboBox1.addItem("SIENA");
		comboBox1.addItem("SIERRA CARBONERA");
		comboBox1.addItem("SIERRA MINISTRA");
		comboBox1.addItem("SIMANCAS");
		comboBox1.addItem("SOLDADO DE JOSE MARIA REY");
		comboBox1.addItem("URUGUAY");
		comboBox1.addItem("UTEBO");
		comboBox1.addItem("VILLARDONDIEGO");
		comboBox1.addItem("VIÑA VIRGEN");
		comboBox1.addItem("VELEZ RUBIO");
		comboBox1.addItem("YUSTE");
		comboBox1.addItem("ZAZUAR");
		lblRepetirPassword = new JLabel("Calle:");
		contentPane.add(lblRepetirPassword);
		lblRepetirPassword.setBounds(50,160,100,20);
		//Escoger Pais
		JComboBox<String> comboBox = new JComboBox<String>();
		contentPane.add(comboBox);
		comboBox.setBounds(170,190,350,20);
		comboBox.addItem("");
		comboBox.addItem("28001");
		comboBox.addItem("28002");
		comboBox.addItem("28003");
		comboBox.addItem("28004");
		comboBox.addItem("28005");
		comboBox.addItem("28007");
		comboBox.addItem("28008");
		comboBox.addItem("28009");
		comboBox.addItem("28011");
		comboBox.addItem("28012");
		comboBox.addItem("28014");
		comboBox.addItem("28015");
		comboBox.addItem("28017");
		comboBox.addItem("28018");
		comboBox.addItem("28019");
		comboBox.addItem("28020");
		comboBox.addItem("28021");
		comboBox.addItem("28022");
		comboBox.addItem("28023");
		comboBox.addItem("28024");
		comboBox.addItem("28025");
		comboBox.addItem("28026");
		comboBox.addItem("28027");
		comboBox.addItem("28028");
		comboBox.addItem("28029");
		comboBox.addItem("28030");
		comboBox.addItem("28031");
		comboBox.addItem("28032");
		comboBox.addItem("28033");
		comboBox.addItem("28034");
		comboBox.addItem("28035");
		comboBox.addItem("28036");
		comboBox.addItem("28037");
		comboBox.addItem("28038");
		comboBox.addItem("28039");
		comboBox.addItem("28041");
		comboBox.addItem("28042");
		comboBox.addItem("28043");
		comboBox.addItem("28044");
		comboBox.addItem("28045");
		comboBox.addItem("28047");
		comboBox.addItem("28048");
		comboBox.addItem("28050");
		comboBox.addItem("28053");
		lblPais = new JLabel("C\u00F3digo Postal: ");
		contentPane.add(lblPais);
		lblPais.setBounds(50,190,100,20);

		//Etiqueta REGISTRO
		lblRegistro = new JLabel("BUSCADOR");
		contentPane.add(lblRegistro);
		lblRegistro.setBounds(255,30,100,20);

		contentPane.setSize(400,400); 
		contentPane.setVisible(true);
		contentPane.setLayout(null);

		btnRegistrarse = new JButton("Buscar");
		contentPane.add(btnRegistrarse, BorderLayout.EAST);
		btnRegistrarse.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				int cont = 0;
				String nombre = (String)comboBox4.getSelectedItem();
				String distrito = (String)comboBox3.getSelectedItem();
				String barrio = (String)comboBox2.getSelectedItem();
				String calle = (String)comboBox1.getSelectedItem();
				String cp = (String)comboBox.getSelectedItem();
				Resultado.nombre = nombre;
				Resultado.distrito = distrito;
				Resultado.barrio = barrio;
				Resultado.calle = calle;
				Resultado.cp = cp;
				if(nombre.equals("")) cont++;
				if(distrito.equals("")) cont++;
				if(barrio.equals("")) cont++;
				if(calle.equals("")) cont++;
				if(cp.equals("")) cont++;
				if(cont==5) JOptionPane.showMessageDialog(null,"Seleccione al menos 1 opción","Mensaje de Error",JOptionPane.ERROR_MESSAGE);
				else {
					ArrayList<Site> sitios = Init.sentencia(nombre, distrito, barrio, calle, cp);
					if(sitios.isEmpty()) JOptionPane.showMessageDialog(null,"No hay coincidencias","Mensaje de Error",JOptionPane.ERROR_MESSAGE);
					else {
						Resultado.lista = sitios;
						Resultado.num = sitios.size();
						frame.setVisible(false);
						Resultado.main(null);
					}	
				}
			}
		});
		btnRegistrarse.setForeground(new Color(0, 0, 0));
		btnRegistrarse.setBackground(new Color(240, 240, 240));
		btnRegistrarse.setBounds(215, 240, 150, 30);
		contentPane.add(btnRegistrarse);

	}
}
