export const SELECT_STATION_FROM = 'SELECT_STATION_FROM';
export const SELECT_STATION_TO = 'SELECT_STATION_TO';

export const FETCH_STATIONS_FROM_BY_DISTRICT_START = 'FETCH_STATIONS_FROM_BY_DISTRICT_START';
export const FETCH_STATIONS_FROM_BY_DISTRICT_SUCCESS = 'FETCH_STATIONS_FROM_BY_DISTRICT_SUCCESS';
export const FETCH_STATIONS_FROM_BY_DISTRICT_FAIL = 'FETCH_STATIONS_FROM_BY_DISTRICT_FAIL';

export const FETCH_STATIONS_FROM_BY_NEIGHBORHOOD_START = 'FETCH_STATIONS_FROM_BY_NEIGHBORHOOD_START';
export const FETCH_STATIONS_FROM_BY_NEIGHBORHOOD_SUCCESS = 'FETCH_STATIONS_FROM_BY_NEIGHBORHOOD_SUCCESS';
export const FETCH_STATIONS_FROM_BY_NEIGHBORHOOD_FAIL = 'FETCH_STATIONS_FROM_BY_NEIGHBORHOOD_FAIL';

export const FETCH_STATIONS_TO_BY_DISTRICT_START = 'FETCH_STATIONS_TO_BY_DISTRICT_START';
export const FETCH_STATIONS_TO_BY_DISTRICT_SUCCESS = 'FETCH_STATIONS_TO_BY_DISTRICT_SUCCESS';
export const FETCH_STATIONS_TO_BY_DISTRICT_FAIL = 'FETCH_STATIONS_TO_BY_DISTRICT_FAIL';

export const FETCH_STATIONS_TO_BY_NEIGHBORHOOD_START = 'FETCH_STATIONS_TO_BY_NEIGHBORHOOD_START';
export const FETCH_STATIONS_TO_BY_NEIGHBORHOOD_SUCCESS = 'FETCH_STATIONS_TO_BY_NEIGHBORHOOD_SUCCESS';
export const FETCH_STATIONS_TO_BY_NEIGHBORHOOD_FAIL = 'FETCH_STATIONS_TO_BY_NEIGHBORHOOD_FAIL';

export const FETCH_DISTRICTS_START = 'FETCH_DISTRICTS_START';
export const FETCH_DISTRICTS_SUCCESS = 'FETCH_DISTRICTS_SUCCESS';
export const FETCH_DISTRICTS_FAIL = 'FETCH_DISTRICTS_FAIL';

export const FETCH_NEIGHBORHOODS_START = 'FETCH_NEIGHBORHOODS_START';
export const FETCH_NEIGHBORHOODS_SUCCESS = 'FETCH_NEIGHBORHOODS_SUCCESS';
export const FETCH_NEIGHBORHOODS_FAIL = 'FETCH_NEIGHBORHOODS_FAIL';

export const FETCH_INTEREST_POINTS_START = 'FETCH_INTEREST_POINTS_START';
export const FETCH_INTEREST_POINTS_SUCCESS = 'FETCH_INTEREST_POINTS_SUCCESS';
export const FETCH_INTEREST_POINTS_FAIL = 'FETCH_INTEREST_POINTS_FAIL';
